[package]
name = "resw"
version = "0.3.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]
edition = "2018"
description = "A library for writing RESSA AST parts to a file"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/FreeMasen/RESW"

[dependencies]
resast = "0.4.0"
log = "0.4"
ress = "0.7"
reqwest = { version = "0.9", optional = true}
flate2 = { version = "1", optional = true}
tar = { version = "0.4", optional = true}
rayon = { version = "1", optional = true}

[dev-dependencies]
ressa = "0.7.0-beta-7"
pretty_env_logger = "0.3"

[features]
default = []
moz_central = ["reqwest", "flate2", "tar", "rayon"]