[package]
name = "resw"
version = "0.4.0-beta-1"
authors = ["Robert Masen <r@robertmasen.pizza>"]
edition = "2018"
description = "A library for writing RESSA AST parts to a file"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/FreeMasen/RESW"

[dependencies]
resast = "0.4.0"
log = "0.4"
ress = "0.7"

[dev-dependencies]
rayon = { version = "1"}
ressa = { git = "https://github.com/FreeMasen/RESSA", branch = "featureless_test262" }
pretty_env_logger = "0.3"

[features]
default = []
moz_central = []
